version: '3.1'

services:

  yourls:
    image: yourls:latest
    container_name: yourls
    restart: unless-stopped
    ports:
      - 8088:80
    expose:
      - 80
    environment:
      YOURLS_SITE: http://0.0.0.0 # please adjust to your domain
      YOURLS_USER: kyle # please adjust
      YOURLS_PASS: thisisjustatest # please adjust
      YOURLS_DB_HOST: mysql
      YOURLS_DB_USER: yourls
      YOURLS_DB_NAME: yourls
      YOURLS_DB_PASS: thisisjustatest # please adjust
    volumes:
      - ./security.conf:/etc/apache2/conf-enabled/security.conf:ro      
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.yourls.rule=Host(`s.ptf.one`)
    #  - traefik.http.services.yourls.loadbalancer.server.port=80
    #  - traefik.docker.network=proxy
    #  # Part for optional traefik middlewares
    #  - traefik.http.routers.CHANGEME.middlewares=local-ipwhitelist@file,authelia@docker     

  mysql:
    image: mysql:latest
    container_name: yourls-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yourls
      MYSQL_USER: yourls
      MYSQL_PASSWORD: thisisjustatest # please adjust
      MYSQL_ROOT_PASSWORD: thisisjustatest # please adjust
    volumes:
      - yourls_mysql:/var/lib/mysql
    #networks:
    #  - proxy

volumes:
  yourls_mysql:
    driver_opts:
      type: nfs
      device: ":/Docker/yourls/mysql"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw

#networks:
#  proxy:
#    external: true
